parameters:
- name: azureSubscription
  type: string
- name: webAppName
  type: string

jobs:
- job: DeployWebApp
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - download: current
      artifact: AngularApp
      displayName: "Download Angular Build Artifact"

    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: "$(Pipeline.Workspace)/AngularApp/*.zip"
        destinationFolder: "$(Pipeline.Workspace)/AngularApp/unzipped"
        cleanDestinationFolder: true
      displayName: "Extract App Bundle"

    - task: AzureWebApp@1
      displayName: "Deploy Angular SSR App"
      inputs:
        azureSubscription: ${{ parameters.azureSubscription }}
        appType: "webAppLinux"
        appName: ${{ parameters.webAppName }}
        package: "$(Pipeline.Workspace)/AngularApp/unzipped"
        runtimeStack: "NODE|20-lts"
        startUpCommand: "npm install --omit=dev && node server/server.mjs"
